name: djangoWork
channels:
  - defaults
dependencies:
  - python=3.11.5
  - pip
  - pip:
    - django==4.2.7
    - requests==2.31.0
    - argon2-cffi==21.3.0
    - argon2-cffi-bindings==21.2.0
    - asyncio-dgram==2.1.2
    - colorama==0.4.6
    - django-bootstrap5==23.3
    - dnspython==2.4.2
    - mcstatus==11.0.1
    - pillow==10.1.0
    - prompt-toolkit==3.0.39
    - wcwidth==0.2.9
    - daphne==4.0.0
    - whitenoise==6.6.0
    - django-tinymce==3.6.1
    - django-js-asset==2.1.0
    - python-dotenv==1.0.0
    - mysqlclient==2.1.1
    - django-jazzmin==2.6.0
    - discord.py==2.3.2
    - django-ranged-response==0.2.0
    - django-simple-captcha==0.5.20
    - six==1.16.0
    - django-resized==1.0.2
    - pandas==2.1.2
    - plotly==5.18.0
